/** Uploaded static asset URLs (webdev storage). */
export const IMG = {
  heroDarkInterior: "/manus-storage/hero-dark-interior_739f4024.jpg",
  interiorMoody: "/manus-storage/interior-moody_6ec0d3af.jpg",
  listingAustinModern: "/manus-storage/listing-austin-modern_741409df.webp",
  listingHillCountryWhite: "/manus-storage/listing-hillcountry-white_5a9e0c46.jpeg",
  listingGracelyn: "/manus-storage/listing-gracelyn_38d8aecd.jpg",
  listingCordillera: "/manus-storage/listing-cordillera_c64c3d56.jpg",
  listingBarnhouse: "/manus-storage/listing-barnhouse_7f3f3269.jpg",
  listingHoustonSunset: "/manus-storage/listing-houston-sunset_55db521d.jpg",
  listingPoolEstate: "/manus-storage/listing-pool-estate_c1433ee3.jpg",
  citySanAntonio: "/manus-storage/city-san-antonio_15388e3a.jpg",
  cityAustin: "/manus-storage/city-austin_127412ff.jpg",
  cityHouston: "/manus-storage/city-houston_9763b83b.jpg",
  cityNewBraunfels: "/manus-storage/city-new-braunfels_9ad0d328.jpg",
  cityDfw: "/manus-storage/city-dfw_7ef7f575.jpg",
  areaBoerne: "/manus-storage/area-boerne_5d6d253c.jpg",
  areaKyle: "/manus-storage/area-kyle_5abc0638.jpg",
  areaAlamoRanch: "/manus-storage/area-alamo-ranch_6b62089f.jpg",
} as const;
